services:

  book-network:
    container_name: book-network
    image: devcoderjava/app-security:1.0.2
    environment:
      - DB_HOST=postgres-sql-bsn
      - DB_PORT=5432
      - DB_NAME=book_social_network
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USER=test
      - MAIL_PASSWORD=test
      - URL_ACTIVATION=http://localhost:8080/activate-account
    ports:
      - 8088:8088
    networks:
      - spring
    depends_on:
      - postgres

  book-network-ui:
    container_name: book-network-ui
    image: devcoderjava/app-network-ui:1.0.1
    ports:
      - 8080:80
    networks:
      - spring
    depends_on:
      - book-network

  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book_social_network
    networks:
      - spring
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring:
    name: spring
    driver: bridge

volumes:
  pgdata: