services:

  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book_social_network
    volumes:
      - ./db:/var/lib/postgresql
    restart: unless-stopped

networks:
  spring-demo:
    driver: bridge

volumes:
  db: