version: '3.9'

services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book_social_network
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    networks:
      - spring-demo
    restart: unless-stopped

  maildev:
    container_name: maildev-dev-sbn
    image: maildev/maildev
    ports:
      - "1080:8080"
      - "1025:1025"

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local