spring:
  mail:
#    host: smtp.gmail.com
#    port: 587
    username: ${MAIL_USER:ali}
    password: ${MAIL_PASSWORD:ali}
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
        transport:
          protocol: smtp
application:
  security:
    jwt:
      secret: ${SECRET_KEY:4a4b4c4d4e4f4g4h4i4j4k4l4m4n4o4p4q4r4s4t4u4v4w4x4y4z}
      expiration: 8640000
  mailing:
    frontend:
      activation-url: ${URL_ACTIVATION:http://localhost:4200/activate-account}
db:
  url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:book_social_network}
  username: ${DB_USER:postgres}
  password: ${DB_PASSWORD:postgres}
server:
  port: 8088